management:
    endpoints:
        web:
            exposure:
                include: '*'
#By default the path for cxf is: /services
cxf:
    #Overriding the default path
    path: /services

pyur:
    servicerouter:
        external-services:
            -
                context-path: de.xconnect.bus.api
                name: enghouse
                endpoint: wswbservice

spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:service_router_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
        default-schema: ''
